package com.bms.pathogold_bms.utility

class AllKeys {
    companion object {

        //payment gateway key id...
        val MERCHANT_ID_RAZORPAY = "MERCHANT_ID_RAZORPAY" //Live merchant id for live url.

         val MERCHANT_ID_RAZORPAY_TEST="rzp_test_mvTEGRpb2vkNNb" //Testing merchant id for production(Testing purpose)
        // val MERCHANT_ID_RAZORPAY="rzp_live_JpCyOwVr6sRRLp" //Live merchant id for production(Testing purpose)
        val LOGO_URL = "https://www.birlamedisoft.com/img/companypro.png"
        val SERVER_MESSAGE = "Server error!"
        val ACCOUNT_IS_NOT_ACTIVATED = "Account is not active..Please make payment to activate account!"
        val ACTIVE = "ACTIVE"
        val SUCCESS = "SUCCESS"
        val INACTIVE = "INACTIVE"
        val LOGIN_VIA = "LOGIN_VIA"
        val VIA_OTP = "VIA_OTP"
        val VIA_USERNAME_PASSWORD = "VIA_USERNAME_PASSWORD"
        val STATIC_LAB_CODE = "J@kfA3j2k33"
        val UNABLE_TO_CONNECT = "Unable to connect...Try after some time! !"
        var NO_INTERNET_AVAILABLE = "No Internet Connection!"
        var SERVICE_NOT_AVAILABLE = "Service not available!"
        var PAYMENT_SERVICE_NOT_AVAILABLE = "Payment service not available."
        var YOUR_BILL_IS_NOT_PREPARED = "Your Bill is not prepared."
        var IS_VIDEO_CALL_LAUNCH = "IS_VIDEO_CALL_LAUNCH"
        var IS_PATIENT_LIST_LAUNCH = "IS_PATIENT_LIST_LAUNCH"
        val DNF = "DNF"
        val LOGIN_TYPE = "LOGIN_TYPE"
        val USER_NAME = "USER_NAME"
        val HSC_ID = "HSC_ID"
        val MOBILE_NO = "MOBILE_NO"
        val LABNAME = "LABNAME"
        val LABNAME_C = "LABNAME_C"
        val PERSON_NAME = "PERSON_NAME"
        val SEX = "GENDER"
        val DOB = "DOB"
        val EMAIL = "EMAIL"
        val ADDRESS = "ADDRESS"
        val USERTYPE = "USERTYPE"
        val TODAYS_DATE = "TODAYS_DATE"
        val ET_USERNAME = "ET_USERNAME"
        val ET_PASSWORD = "ET_PASSWORD"
        val REMEMBER_ME = "REMEMBER_ME"
        val REMEMBER_ME_LOGIN_TYPE = "REMEMBER_ME_LOGIN_TYPE"
        val PATIENT_PROFILE_ID = "PATIENT_PROFILE_ID"
        val PATH = "PATH"
        val SUPPORT_ID = "SUPPORT_ID"
        val LOGO_PATH = "LOGO_PATH"
        val SUPPORT_TOKEN = "SUPPORT_TOKEN"
        val ACCOUNT_STATUS = "ACCOUNT_STATUS"
        val DATA_NOT_FOUND = "Data Not Found!"
        var UNPROPER_RESPONSE = "Something went wrong. Please, Try gain later."
        //var COMPANY_ID = "10"
        var COMPANY_ID = "COMPANY_ID"
        var Consultant = "Consultant"
        var Lab_Technician = "Lab Technician"
        var Phlebotomist = "Phlebotomist"
        var Patient = "Patient"
        var Administrator = "Administrator"
        var Support = "support"
        var SuperAdmin = "SuperAdmin"
        var Reference_Doctor = "Reference Doctor"
        var CollectionCenter = "CollectionCenter"
        var GCM_TOKEN = "GCM_TOKEN"
        val LOCATION_SERVICE_ID = 175
        val ACTION_START_LOCATION_SERVICE = "startLocationService"
        val ACTION_STOP_LOCATION_SERVICE = "stopLocationService"
        val LAST_LATITUDE = "LAST_LATITUDE"
        val LAST_LONGITUDE = "LAST_LONGITUDE"
        val TOTAL_DISTANCE = "0.0"
        val START_TIME = "START_TIME"
        val ENTRY_DATE = "ENTRY_DATE"
        val THIS_FEATURE_ONLY = "This feature is accessible to the phlebotomist only."
        val NOT_AVAILABLE = "Not available."
        val GPS_REQUEST = 100

        val appointment = "appointment"
        val patientregistration = "patientregistration"
        val vital = "vital"
        val fileupload = "fileupload"
        val report_download = "report_download"
        val my_distance = "my_distance"
        val Prescription = "Prescription"
        val videocall = "videocall"
        val vaccination = "vaccination"
        val viewprescription = "viewprescription"
        val dailycashregister = "dailycashregister"
        val reportdetails = "report detail"
        val recent_chat = "recent_chat"
        val BY_DOCTOR_NAME = "BY_DOCTOR_NAME"
        val BY_COLLECTION_CENTER = "BY_COLLECTION_CENTER"
        val BY_PATIENT_NAME = "BY_PATIENT_NAME"
        val BY_STATUS = "BY_STATUS"
        val BILL_AMT = "Bill Amount"
        val PATIENT_COUNT = "Patient Count"
        val RECEIVED_AMT = "Received Amt"
        val TEST_CHARGES = "Test Charges"
        val DISCOUNT = "Discount"
        val BALANCE = "Balance"
        val UNBILLED_AMT = "Unbilled Amt"
        val OTHER_CHARGES = "Other Charges"
        val TODAYS_COLLECTION = "Today's collection"
        val CURRENCY_SYMBOL = "CURRENCY_SYMBOL"
        val DATE_FORMAT = "DATE_FORMAT"
        val RAZOR_PAY="RAZOR_PAY"
        val PAYU="PAYU"
        val PAYU_MERCHANT_KEY="PAYU_MERCHANT_KEY"
        val PAYU_MERCHANT_SALT="PAYU_MERCHANT_SALT"
        val surl = "https://payu.herokuapp.com/success"
        val furl = "https://payu.herokuapp.com/failure"
        val salt = "BX0tdk3dzy"//BMS Salt Key
        val merchantKey = "1UFTvjlW"//BMS Merchant Key

        //val salt = "wia56q6O"//Test Salt Key
        //val merchantKey = "gtKFFx"//Test Merchant Key
    }
}