package com.bms.pathogold_bms.model.login

data class LoginBO (var Status:String="ACTIVE",
               var HSC_ID:String,
               var PatientProfileID:String,
               var TPA:String,
               var TPACompany:String,
               var MobileNo:String,
               var LabName:String,
               var PersonName:String,
               var Sex:String,
               var Dob:String,
               var Email:String,
               var Address:String,
               var UserType:String,
               var LabName_C:String,
               var UserName:String,
               var appointment:String,
               var patientregistration:Boolean,
               var vital: Boolean,
               var fileupload: Boolean,
               var report_download: Boolean,
               var my_distance: Boolean,
               var Prescription: Boolean,
               var videocall: Boolean,
               var vaccination: Boolean,
               var viewprescription: Boolean,
               var currency:String,
               var Dailycashregister:Boolean,
               var Reportdetail:Boolean,
               var marchantid:String,
               var UPIID:String,
               var Path:String,
               var supportuserid:String,
               var support_token:String,
               var logoPath:String,
               var Payu_marchantid :String,
               var Payu_marchantsaltid :String,
               var balance :String,
               var companyid:String,
        )